# Generated by Django 4.1.7 on 2023-03-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suprimentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='status',
            field=models.CharField(choices=[('1', 'Ativo'), ('2', 'Inativo'), ('3', '...')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='processolicitatorio',
            name='status',
            field=models.CharField(choices=[('1', 'Ativo'), ('2', 'Inativo'), ('3', '...')], default=1, max_length=1),
        ),
    ]
