# Generated by Django 4.1.7 on 2023-03-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suprimentos', '0002_alter_material_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='status',
            field=models.CharField(choices=[('1', 'Ativo'), ('2', 'Inativo')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='processolicitatorio',
            name='status',
            field=models.CharField(choices=[('1', 'Ativo'), ('2', 'Inativo')], default=1, max_length=1),
        ),
    ]
