# Generated by Django 4.1.7 on 2023-03-13 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suprimentos', '0003_alter_material_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPUCompleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('pecas', models.ManyToManyField(to='suprimentos.material')),
                ('proc_licitatorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suprimentos.processolicitatorio')),
            ],
        ),
    ]
