# Generated by Django 4.1.7 on 2023-03-14 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suprimentos', '0005_cpucompleto_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ('status', 'proc_licitatorio', 'nome'), 'verbose_name': 'Material', 'verbose_name_plural': 'Materiais'},
        ),
        migrations.AlterModelOptions(
            name='processolicitatorio',
            options={'ordering': ('status',), 'verbose_name': 'Processo', 'verbose_name_plural': 'Processos'},
        ),
        migrations.AlterField(
            model_name='material',
            name='proc_licitatorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='suprimentos.processolicitatorio', verbose_name='processo'),
        ),
    ]
