# Generated by Django 4.1.7 on 2023-03-14 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suprimentos', '0006_alter_material_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='proc_licitatorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiais', to='suprimentos.processolicitatorio', verbose_name='processo'),
        ),
    ]
