# Generated by Django 4.1.7 on 2023-03-15 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('setores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indentificador', models.CharField(blank=True, max_length=24, null=True)),
                ('codigo_sharepoint', models.CharField(blank=True, max_length=10, null=True)),
                ('configuracao', models.TextField(blank=True, null=True)),
                ('serial_windows', models.CharField(blank=True, max_length=25, null=True)),
                ('serial_office', models.CharField(blank=True, max_length=25, null=True)),
                ('ip', models.CharField(blank=True, max_length=12, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=12, null=True)),
                ('patrimonio', models.CharField(blank=True, max_length=10, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo', models.CharField(choices=[('01', 'COMPUTADOR'), ('02', 'NOTEBOOK'), ('03', 'ROTEADOR'), ('04', 'MIKROTIK')], default='01', max_length=2)),
                ('responsavel', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('1', 'Ativo'), ('2', 'Inativo'), ('3', 'Reserva'), ('4', 'Baixa Patrimônio')], default='1', max_length=1)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('album', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model', to='dashboard.imagemalbum')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setores.setor')),
            ],
            options={
                'ordering': ['setor', 'indentificador', 'status', 'patrimonio'],
            },
        ),
    ]
