# Generated by Django 4.1.7 on 2023-03-14 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setores', '0003_alter_setor_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuracao', models.TextField()),
                ('serial_windows', models.CharField(blank=True, max_length=25, null=True)),
                ('serial_office', models.CharField(blank=True, max_length=25, null=True)),
                ('ip', models.CharField(blank=True, max_length=12, null=True)),
                ('patrimonio', models.CharField(blank=True, max_length=10, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo', models.CharField(choices=[('01', 'COMPUTADOR'), ('02', 'NOTEBOOK'), ('03', 'ROTEADOR'), ('04', 'MIKROTIK')], default='01', max_length=2)),
                ('responsavel', models.CharField(blank=True, max_length=200, null=True)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setores.setor')),
            ],
        ),
    ]
