# Generated by Django 4.1.7 on 2023-03-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0002_alter_equipamento_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='status',
            field=models.CharField(choices=[('1', 'Ativo'), ('2', 'Inativo'), ('3', 'Reserva'), ('4', 'Baixa Patrimônio')], default='1', max_length=1),
        ),
    ]
