# Generated by Django 4.1.7 on 2023-03-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0003_equipamento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='codigo_sharepoint',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='indentificador',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='configuracao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
