# Generated by Django 4.1.7 on 2023-03-20 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0003_imagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipamento',
            options={'ordering': ['id', 'setor', 'indentificador', 'status', 'patrimonio']},
        ),
        migrations.AlterField(
            model_name='imagem',
            name='equipamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipamentos.equipamento'),
        ),
    ]
