# Generated by Django 4.1.7 on 2023-03-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0004_equipamento_codigo_sharepoint_equipamento_descricao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipamento',
            options={'ordering': ['setor', 'indentificador', 'status', 'patrimonio']},
        ),
        migrations.AddField(
            model_name='equipamento',
            name='mac_address',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
