# Generated by Django 4.1.7 on 2023-03-10 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diretorias', '0002_diretoria_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDiretoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='diretoria',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diretorias.tipodiretoria'),
        ),
    ]
