# Generated by Django 4.1.7 on 2023-03-14 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diretorias', '0003_tipodiretoria_alter_diretoria_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diretoria',
            options={'ordering': ['nome', 'tipo'], 'verbose_name': 'Diretoria', 'verbose_name_plural': 'Diretorias'},
        ),
        migrations.AlterModelOptions(
            name='tipodiretoria',
            options={'ordering': ['nome'], 'verbose_name': 'Tipo', 'verbose_name_plural': 'Tipos'},
        ),
    ]
