# Generated by Django 4.1.7 on 2023-03-24 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laudos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laudomaterial',
            name='numero_laudo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='materiais', to='laudos.laudo'),
        ),
    ]
