# Generated by Django 4.1.7 on 2023-03-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laudos', '0005_alter_laudomaterial_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laudo',
            name='status',
            field=models.CharField(blank=True, choices=[('01', 'Aberto'), ('02', 'Finalizado')], default='01', max_length=2, null=True),
        ),
    ]
