# Generated by Django 4.1.7 on 2023-04-10 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('setores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(max_length=10, unique=True)),
                ('funcionario', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, choices=[('1', 'Aberto'), ('2', 'Pendente'), ('3', 'Finalizado')], max_length=1, null=True)),
                ('tipo_contato', models.CharField(blank=True, choices=[('1', 'Contato Telefônico'), ('2', 'Contato por WhatsApp'), ('3', 'Contato por Email'), ('4', 'Contato Pessoalmente')], max_length=1, null=True)),
                ('contato', models.CharField(blank=True, max_length=11, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setor', to='setores.setor')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tecnico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data_criacao', 'status'],
            },
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico_realizado', models.TextField(blank=True, null=True)),
                ('status_atendimento', models.CharField(blank=True, choices=[('1', 'Aberto'), ('2', 'Aguardando Laudo'), ('3', 'Aguardando Visita Tecnica'), ('4', 'Aguardando Tecnico Qualificado'), ('5', 'Aguardando Empresa Terceirizada'), ('6', 'Finalizado')], max_length=1, null=True)),
                ('tipo_atencimento', models.CharField(blank=True, choices=[('1', 'Presencial'), ('2', 'Remoto')], max_length=1, null=True)),
                ('data_atendimento', models.DateTimeField(auto_now_add=True, null=True)),
                ('ordemservico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atendimentos.ordemservico')),
            ],
        ),
    ]
