# Generated by Django 4.1.7 on 2023-04-10 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atendimento',
            old_name='tipo_atencimento',
            new_name='tipo_atendimento',
        ),
    ]
