# Generated by Django 4.1.7 on 2023-03-15 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diretorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('responsavel', models.CharField(blank=True, max_length=200, null=True)),
                ('telefone', models.CharField(blank=True, max_length=9, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('diretoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diretorias.diretoria')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['diretoria', 'nome'],
            },
        ),
    ]
