# Generated by Django 4.1.7 on 2023-03-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setor',
            name='endereco',
            field=models.TextField(blank=True, null=True),
        ),
    ]
