# Generated by Django 4.1.7 on 2023-03-14 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setores', '0002_setor_endereco'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setor',
            options={'ordering': ['diretoria', 'nome'], 'verbose_name': 'Setor', 'verbose_name_plural': 'Setores'},
        ),
    ]
