# Generated by Django 4.1.7 on 2023-03-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profiles_pic'),
        ),
    ]
